### ISSUE TITLE
Membuat Desain Rangkaian

### ISSUE THREAD

**Issue by SuryaSaptaAdiN** [SuryaSaptaAdiN/Project_Audio-Player-Menggunakan-Mikrokontroler-AVR-untuk-Piano-Elektrik#1]
Desain diberi keterangan, dikasih link upload terbaru

**Comment by Ahanz55** [comment]
Opo seh :")

**Comment by Ahanz55** [comment]
![Image](https://github.com/SuryaSaptaAdiN/Project_Audio-Player-Menggunakan-Mikrokontroler-AVR-untuk-Piano-Elektrik/assets/124276049/8161cda8-1cf7-4b6a-9654-2f82b05f6a2a)

**Comment by Ahanz55** [comment]
![Image](https://github.com/SuryaSaptaAdiN/Project_Audio-Player-Menggunakan-Mikrokontroler-AVR-untuk-Piano-Elektrik/assets/124276049/c4ed2827-6884-44bb-9559-de6d5f35e167)

**Comment by SuryaSaptaAdiN** [comment]
revisi lagi mas

**Comment by Ahanz55** [comment]
![Image](https://github.com/SuryaSaptaAdiN/Project_Audio-Player-Menggunakan-Mikrokontroler-AVR-untuk-Piano-Elektrik/assets/124276049/025c0720-d8a6-41d5-9ea9-cbcab636bcd5)
