### ISSUE TITLE
Membuat PCB

### ISSUE THREAD

**Issue by SuryaSaptaAdiN** [SuryaSaptaAdiN/Project_Audio-Player-Menggunakan-Mikrokontroler-AVR-untuk-Piano-Elektrik#2]
Desain PCB seperti pakai Shield jadi langsung dipakai dan terhubung ke Push Button

**Comment by gusma123** [comment]
[Piano.pdf](https://github.com/SuryaSaptaAdiN/Project_Audio-Player-Menggunakan-Mikrokontroler-AVR-untuk-Piano-Elektrik/files/15285778/Piano.pdf)

**Comment by gusma123** [comment]
[Piano.zip](https://github.com/SuryaSaptaAdiN/Project_Audio-Player-Menggunakan-Mikrokontroler-AVR-untuk-Piano-Elektrik/files/15285781/Piano.zip)

**Comment by gusma123** [comment]
[Piano.zip](https://github.com/SuryaSaptaAdiN/Project_Audio-Player-Menggunakan-Mikrokontroler-AVR-untuk-Piano-Elektrik/files/15285783/Piano.zip)
