### ISSUE TITLE
Membuat Desain 3D

### ISSUE THREAD

**Issue by SuryaSaptaAdiN** [SuryaSaptaAdiN/Project_Audio-Player-Menggunakan-Mikrokontroler-AVR-untuk-Piano-Elektrik#3]
Desain 3D diupoad dalam bentuk yang detail dan sampai bagian luar seperti baterai, mikro, dan push button, beri keterangan setiap detail pada gambar

**Comment by Manyoe29** [comment]
https://drive.google.com/drive/folders/1oqpe9ZGwvtJtPll9_H5oFUw0zMhtc_kb?usp=sharing

**Comment by Manyoe29** [comment]
![model](https://github.com/SuryaSaptaAdiN/Project_Audio-Player-Menggunakan-Mikrokontroler-AVR-untuk-Piano-Elektrik/assets/168956595/7f4dd867-bd86-47c7-b6c7-6e8aa7a87ba6)
![model (1)](https://github.com/SuryaSaptaAdiN/Project_Audio-Player-Menggunakan-Mikrokontroler-AVR-untuk-Piano-Elektrik/assets/168956595/4afc7d96-91e6-4a65-9201-adba1caef342)
![model (2)](https://github.com/SuryaSaptaAdiN/Project_Audio-Player-Menggunakan-Mikrokontroler-AVR-untuk-Piano-Elektrik/assets/168956595/a6fc68a1-84dd-43d7-a4a9-ce4e568db919)
![model (3)](https://github.com/SuryaSaptaAdiN/Project_Audio-Player-Menggunakan-Mikrokontroler-AVR-untuk-Piano-Elektrik/assets/168956595/0184b1e4-a95b-4248-beee-c93df2d8ad01)
![model (4)](https://github.com/SuryaSaptaAdiN/Project_Audio-Player-Menggunakan-Mikrokontroler-AVR-untuk-Piano-Elektrik/assets/168956595/f1698c2c-e3eb-4d4f-bd8d-adc0a7040754)
